### ISSUE TITLE
get_dynamic_quantum_architecture doesn't work properly

### ISSUE THREAD

**Issue by Eyal-Leviatan** [iqm-finland/qiskit-on-iqm#121] opened 2024-09-23 14:37 UTC
`
from iqm import qiskit_iqm

server_url = "https://cocos.resonance.meetiqm.com/garnet"
api_token="..."

provider = qiskit_iqm.IQMProvider(server_url, token=api_token)
backend = provider.get_backend()
client = backend.client
client.get_dynamic_quantum_architecture()
`

returns:
HTTPError: 404 Client Error: Not Found for url: https://cocos.resonance.meetiqm.com/garnet/api/quantum-computers/v1/calibration/default/gates

**Comment by freetonik** [comment] 2024-09-24 04:54
Hello,
IQM Resonance is not using the latest version of IQM server software, and does not support dynamic quantum architecture yet.

**Comment by Eyal-Leviatan** [comment] 2024-09-24 06:53
I was looking for calibration information. I was able to get it by running:

`result = requests.get(  # notice a different base url here
    join("https://api.resonance.meetiqm.com/quantum-computers/v1/garnet/calibrations"),
    headers=client._default_headers()
).json()`

Is there a higher-level functionality of IQMClient that does this for me?

**Comment by JMuff22** [comment] 2024-09-24 07:06
An implementation was added here https://github.com/iqm-finland/iqm-client/pull/91 for reference. As far as I am aware there is no in built functionality for this in `IQMClient` and I have used the method you showed above.

**Comment by Eyal-Leviatan** [comment] 2024-09-24 07:59
Right, but the URL there (os.path.join(self._base_url, 'calibration')) will not work, since _base_rul is "https://cocos.resonance.meetiqm.com/garnet" (as per the documentation of how to send jobs).
It works for:
_base_url = "https://api.resonance.meetiqm.com/quantum-computers/v1/garnet"
though.

Thanks anyway

**Comment by jkotilahti** [comment] 2024-11-15 14:35
IQM Resonance now supports `get_dynamic_quantum_architecture`, so the error from the issue description should not happen anymore. 

We also now improved the error messages for these kinds of errors (https://github.com/iqm-finland/iqm-client/pull/145), so that it would be more clear that the error is caused by version incompatibility. And the idea about obtaining calibration data using IQM Client is in our backlog as @Aerylia said, and may be added in the future. 

Closing this issue now, feel free to reopen if you think something else is still needed for this.

**Closed by jkotilahti** 2024-11-15 14:35 UTC
